import React, { useEffect, useState, useRef } from 'react';
import { useAuth } from '@/hooks/useAuth';
import TodaysMeals from '@/components/MealsComponents/TodaysMeals';
import AICalendarMealPlanner from '@/components/MealsComponents/AICalendarMealPlanner';
import GroceryList from '@/components/MealsComponents/GroceryList';
import LogMeal from '@/components/MealsComponents/LogMeal';
import AISearchRecipe from '@/components/MealsComponents/AISearchRecipe';
import EdamamRecipeSearchTester from '@/components/MealsComponents/EdamamRecipeSearchTester';
import EdamamNutritionAnalysisTester from '@/components/MealsComponents/EdamamNutritionAnalysisTester';
import EdamamFoodDatabaseTester from '@/components/MealsComponents/EdamamFoodDatabaseTester';
import EdamamWeeklyMealPlan from '@/components/MealsComponents/EdamamWeeklyMealPlan';
import { supabase } from '@/integrations/supabase/client';
import { Loader2 } from 'lucide-react';

const Meals: React.FC = () => {
  const { user } = useAuth();
  const userId = user?.id;
  const today = new Date();
  const todayStr = today.toISOString().slice(0, 10);
  const weekStart = (() => {
    const d = new Date(today);
    d.setDate(d.getDate() - d.getDay() + 1); // Monday as start
    return d.toISOString().slice(0, 10);
  })();

  const [nutritionPrefs, setNutritionPrefs] = useState<any>(null);
  const [prefsLoading, setPrefsLoading] = useState(true);

  // AI Recipe Search state (for modularity, can be moved to a custom hook)
  const [recipeQuery, setRecipeQuery] = useState('');
  const [recipeLoading, setRecipeLoading] = useState(false);
  const [recipeResults, setRecipeResults] = useState<any[]>([]);
  const [recipeError, setRecipeError] = useState('');
  const [savedRecipes, setSavedRecipes] = useState<any[]>([]);
  const [hoveredSavedRecipe, setHoveredSavedRecipe] = useState<any | null>(null);
  const [savedRecipeTooltipPos, setSavedRecipeTooltipPos] = useState<{ x: number, y: number } | null>(null);
  const savedRecipeTooltipTimeout = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    const fetchPrefs = async () => {
      if (!userId) return;
      setPrefsLoading(true);
      const { data } = await supabase
        .from('user_nutrition_preferences')
        .select('*')
        .eq('user_id', userId)
        .single();
      setNutritionPrefs(data || {});
      setPrefsLoading(false);
    };
    fetchPrefs();
  }, [userId]);

  // AI Recipe Search handlers
  const handleRecipeSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    setRecipeError('');
    setRecipeLoading(true);
    setRecipeResults([]);
    try {
      const res = await fetch('/api/generate-recipe', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: recipeQuery, user_id: userId }),
      });
      if (!res.ok) throw new Error('Failed to search recipes');
      const data = await res.json();
      setRecipeResults(Array.isArray(data) ? data : []);
    } catch (err: any) {
      setRecipeError(err.message || 'Error searching recipes');
    }
    setRecipeLoading(false);
  };
  const handleSaveRecipe = (recipe: any) => {
    setSavedRecipes(prev => [...prev, recipe]);
  };

  if (!userId) {
    return <div className="flex flex-col items-center justify-center min-h-[60vh] text-lg text-gray-600">Please log in to view your meals.</div>;
  }
  if (prefsLoading) {
    return <div className="flex flex-col items-center justify-center min-h-[60vh] text-lg text-gray-600"><Loader2 className="w-8 h-8 animate-spin mb-2 text-green-500" /> Loading your nutrition preferences...</div>;
  }

  return (
    <div className="bg-gradient-to-br from-blue-50 to-green-50 min-h-screen w-full py-12">
      <div className="max-w-6xl mx-auto flex flex-col gap-12">
        {/* Today's Meals and Nutrition Card */}
        <div className="flex flex-col md:flex-row gap-8 w-full">
          <div className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-8">
            <TodaysMeals userId={userId} todayStr={todayStr} />
          </div>
          {/* Nutrition Card - you may need to restore this as a separate component if it was before */}
          {/* <TodaysNutritionCard nutritionPrefs={nutritionPrefs} /> */}
        </div>
        {/* AI Meal Plan Calendar */}
        <div>
          <h2 className="text-2xl font-bold text-blue-900 mb-2">Your AI Meal Plan Calendar</h2>
          <p className="text-gray-600 mb-4">This calendar shows your personalized meal plan generated by the AI, based on your preferences and logged meals.</p>
          <AICalendarMealPlanner userId={userId} weekStart={weekStart} nutritionPrefs={nutritionPrefs || {}} />
        </div>
        {/* Edamam Demo Meal Plan Calendar */}
        <div>
          <h2 className="text-2xl font-bold text-green-700 mb-2 flex items-center gap-2"><span>📅</span> Edamam Demo Meal Plan Calendar</h2>
          <p className="text-gray-600 mb-4">This calendar is a demo using the Edamam API, showing example meal plans from Edamam's recipe database.</p>
          <EdamamWeeklyMealPlan nutritionPrefs={nutritionPrefs || {}} handleRegenerateDay={() => {}} />
        </div>
        {/* Grocery List, Log a Meal, AI Recipe Search */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 w-full">
          <GroceryList userId={userId} weekStart={weekStart} />
          <LogMeal userId={userId} todayStr={todayStr} />
          <AISearchRecipe
            recipeQuery={recipeQuery}
            setRecipeQuery={setRecipeQuery}
            recipeLoading={recipeLoading}
            recipeResults={recipeResults}
            recipeError={recipeError}
            handleRecipeSearch={handleRecipeSearch}
            handleSaveRecipe={handleSaveRecipe}
            savedRecipes={savedRecipes}
            hoveredSavedRecipe={hoveredSavedRecipe}
            setHoveredSavedRecipe={setHoveredSavedRecipe}
            savedRecipeTooltipPos={savedRecipeTooltipPos}
            setSavedRecipeTooltipPos={setSavedRecipeTooltipPos}
            savedRecipeTooltipTimeout={savedRecipeTooltipTimeout}
          />
        </div>
        {/* Edamam Testers */}
        <EdamamRecipeSearchTester />
        <EdamamNutritionAnalysisTester />
        <EdamamFoodDatabaseTester />
      </div>
    </div>
  );
};

export default Meals;
