// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vafgznielwbuumhmahtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZmd6bmllbHdidXVtaG1haHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjQzNjcsImV4cCI6MjA2NjUwMDM2N30.DNlg_8Xa4-lOir94K5C6CfeFRkLGf3NGgRYsOG41eZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);