name: Reset Habits (Manual)

on:
  workflow_dispatch:  # Allows you to trigger this manually from the GitHub Actions tab

jobs:
  reset-habits:
    runs-on: ubuntu-latest
    steps:
      - name: Reset habits in Supabase
        run: |
          curl -X PATCH "https://vafgzniebwbuunhmahtk.supabase.co/rest/v1/user_habits?completed_today=is.true" \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{"completed_today": false}'