name: Reset Habits Daily

on:
  schedule:
    - cron: '0 9 * * *'  # 9:00 AM UTC daily
  # You can keep workflow_dispatch for manual testing if you want
  workflow_dispatch:

jobs:
  reset-habits:
    runs-on: ubuntu-latest
    steps:
      - name: Reset habits in Supabase
        run: |
          curl -X PATCH "https://vafgznielwbuumhmahtk.supabase.co/rest/v1/user_habits?completed_today=is.true" \
            -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{"completed_today": false}'